function inZone = particle_in_zone(location, zone_left, zone_rite, zone_bot, zone_top)
    inZone = (location(:,1) >= zone_left ...
            & location(:,1) <= zone_rite ...
            & location(:,2) >= zone_bot  ...
            & location(:,2) <= zone_top);
end